%YAML 1.1
---
#####################
## GLOBAL SETTINGS ##
#####################
violation-logs-path: /tigress/jdh4/utilities/job_defense_shield/violations
reply-to: rcsystems@princeton.edu
greeting-method: getent
workday-method: usa
jobstats-module-path: /usr/local/bin/jobstats
admin-reports:
  - halverson@princeton.edu

################################
## ALERT: SHOULD BE USING MIG ##
################################
should-be-using-mig:
  cluster: della
  partition: gpu
  excluded_users:
    - aturing
    - jzp
    - einstein


#########################
## ZERO UTIL GPU HOURS ##
#########################
zero-util-gpu-hours:
  cluster: della
  partitions:
    - gpu
    - pli-c
    - pli
  min_run_time: 0               # minutes
  gpu_hours_threshold_user: 24  # hours
  gpu_hours_threshold_admin: 24 # hours
  max_num_jobid: 2              # count


############################
## TOO MANY CORES PER GPU ##
############################
too-many-cores-per-gpu:
  cluster: della
  cluster_name: "Della (PLI)"
  partitions:
    - pli
    - pli-c
    - pli-p
  excluded_users:
    - aturing
    - einstein
  cores_per_gpu_target: 12
  cores_per_gpu_limit: 24
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu


########################
## LOW CPU EFFICIENCY ##
########################
low-cpu-efficiency:
  cluster: della
  cluster_name: "Della (cpu)"
  partitions:
    - cpu
  eff_thres_pct: 60
  eff_target_pct: 90 
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 15
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-cpu-efficiency:
  cluster: della
  cluster_name: "Della (physics)"
  partitions:
    - physics
  eff_thres_pct: 60
  eff_target_pct: 90
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 3
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-cpu-efficiency:
  cluster: stellar
  cluster_name: "Stellar (Intel)"
  partitions:
    - all
    - pppl
    - pu
    - serial
  eff_thres_pct: 60
  eff_target_pct: 90
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 15
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu


########################
## LOW GPU EFFICIENCY ##
########################
low-gpu-efficiency:
  cluster: della
  cluster_name: "Della (gpu)"
  partitions:
    - gpu
  eff_thres_pct: 15
  eff_target_pct: 50 
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 15
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-gpu-efficiency:
  cluster: della
  cluster_name: "Della (pli-c)"
  partitions:
    - pli-c
  eff_thres_pct: 40
  eff_target_pct: 75
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 5
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu
    - msbc@princeton.edu

low-gpu-efficiency:
  cluster: della
  cluster_name: "Della (pli)"
  partitions:
    - pli
  eff_thres_pct: 40
  eff_target_pct: 75
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 5
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu
    - msbc@princeton.edu


#######################
## EXCESS CPU MEMORY ##
#######################
excess-cpu-memory:
  tb_hours_per_day: 10
  ratio_threshold: 0.35
  mean_ratio_threshold: 0.35
  median_ratio_threshold: 0.35
  num_top_users: 10
  clusters:
    - della
  partition:
    - cpu
  combine_partitions: False
  cores_per_node: 28
  excluded_users:
    - aturing
    - einstein
    - vonholdt
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu

excess-cpu-memory:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 10
  clusters:
    - della
  partition:
    - datasci
  combine_partitions: False
  cores_per_node: 10000
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com

excess-cpu-memory:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 5
  clusters:
    - stellar
  partition:
    - all
    - pppl
    - pu
    - serial
  combine_partitions: False
  cores_per_node: 76.8
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
