%YAML 1.1
---

#####################
## GLOBAL SETTINGS ##
#####################

jobstats-module-path: /hpc/utils/jobstats
jobstats-config-path: /hpc/utils/jobstats

violation-logs-path: /hpc/utils/jds/logs
email-files-path: /hpc/utils/jds/email

#email-method: "simple"
#email-domain-name: "@mcw.edu"
email-method: ldap
greeting-method: ldap
ldap-server: ldap01.rcc.mcw.edu
ldap_uri: ldap://ldap01.rcc.mcw.edu
ldap_starttls: True
ldap-dn: "cn=ldapbind,ou=UtilityUsers,dc=rcc,dc=mcw,dc=edu"
ldap-password: "REPLACE_WITH_REAL_PASSWORD"
ldap-base-dn: "ou=Users,dc=rcc,dc=mcw,dc=edu"
ldap-uid: "cn"
ldap-mail: "mail"
ldap-displayname: "displayName"

sender: rcc_admin@mcw.edu
reply-to: help-rcc@mcw.edu

workday-method: always

verbose: False
show-empty-reports: True

report-emails:
  - rcc_systems@mcw.edu


##################################
## CANCEL LOW GPU UTILIZATION   ##
##################################

cancel-zero-gpu-jobs-1:
  cluster: hpc2020

  partitions:
    - gpu

  sampling_period_minutes: 15
  first_warning_minutes: 60
  second_warning_minutes: 105
  cancel_minutes: 120

  sliding_warning_minutes: 240
  sliding_cancel_minutes: 300
  
  util_thres: 10
  warning_frac: 0.25
  #  max_interactive_hours: 8
  # max_interactive_gpus: 1
  email_file_first_warning: "cancel_gpu_jobs_warning_1.txt"
  email_file_second_warning: "cancel_gpu_jobs_warning_2.txt"
  email_file_cancel: "cancel_gpu_jobs_scancel_3.txt"
  email_file_sliding_warning: "cancel_gpu_jobs_sliding_warning.txt"
  email_file_sliding_cancel:  "cancel_gpu_jobs_sliding_cancel.txt"

  jobid_cache_path: /hpc/utils/jds/cache

  do_not_cancel: True
  warnings_to_admin: True

  excluded_users:
    - maflister
    - wbranson
    - mkeith

  admin_emails:
    - bgizelar@mcw.edu

  enabled: True

##################################
## ZERO GPU UTILIZATION HOURS   ##
##################################

zero-util-gpu-hours-1:
  cluster: hpc2020

  partitions:
    - gpu

  min_run_time: 30
  gpu_hours_threshold_user: 12
  gpu_hours_threshold_admin: 8
  max_num_jobid: 5

  excluded_users:
    - bgizelar
    - maflister
    - wbranson
    - mkeith

  email_file: "zero_util_gpu_hours.txt"

  admin_emails:
    - bgizelar@mcw.edu

  enabled: True

##################################
## LOW GPU EFFICIENCY           ##
##################################

low-gpu-efficiency-1:
  cluster: hpc2020

  partitions:
    - gpu

  min_run_time: 30
  eff_thres_pct: 30
  eff_target_pct: 60
  absolute_thres_hours: 25
  proportion_thres_pct: 1
  num_top_users: 20

  excluded_users:
    - bgizelar
    - maflister
    - wbranson
    - mkeith

  email_file: "low_gpu_efficiency.txt"

  admin_emails:
    - bgizelar@mcw.edu

  enabled: True


##################################
## EXCESS CPU MEMORY           ##
##################################

excess-cpu-memory-1:
  cluster: hpc2020

  partitions:
    - normal
    - bigmem

  min_run_time: 60
  tb_hours_threshold: 10
  ratio_threshold: 0.20
  mean_ratio_threshold: 0.20
  median_ratio_threshold: 0.20
  num_top_users: 15
  num_jobs_display: 10
 
  excluded_users:
    - bgizelar
    - maflister
    - wbranson
    - mkeith

  email_file: "excess_cpu_memory.txt"

  admin_emails:
    - bgizelar@mcw.edu

  enabled: True


##################################
## LOW CPU EFFICIENCY           ##
##################################

low-cpu-efficiency-1:
  cluster: hpc2020

  partitions:
    - normal
    - bigmem

  min_run_time: 60
  eff_thres_pct: 40
  absolute_thres_hours: 100
  eff_target_pct: 90
  proportion_thres_pct: 1
  num_top_users: 20

  excluded_users:
    - bgizelar
    - maflister
    - wbranson
    - mkeith

  email_file: "low_cpu_efficiency.txt"

  admin_emails:
    - bgizelar@mcw.edu

  enabled: True


##################################
## ZERO CPU UTILIZATION         ##
##################################

zero-cpu-utilization-1:
  cluster: hpc2020

  partitions:
    - normal
    - bigmem

  min_run_time: 30
  cpu_hours_threshold: 5

  excluded_users:
    - bgizelar
    - maflister
    - wbranson
    - mkeith

  email_file: "zero_cpu_utilization.txt"

  admin_emails:
    - bgizelar@mcw.edu

  enabled: True

##################################
## EXCESSIVE TIME LIMITS        ##
##################################

excessive-time-cpu-1:
  cluster: hpc2020

  partitions:
    - normal
    - bigmem

  min_run_time: 61
  absolute_thres_hours: 500
  overall_ratio_threshold: 0.2
  mean_ratio_threshold: 0.2
  median_ratio_threshold: 0.2
  num_top_users: 10
  num_jobs_display: 10

  excluded_users:
    - bgizelar
    - maflister
    - wbranson
    - mkeith
    - ychi

  email_file: "excessive_time.txt"

  admin_emails:
    - bgizelar@mcw.edu

  enabled: True
