%YAML 1.1
---
#####################
## GLOBAL SETTINGS ##
#####################
violation-logs-path: /tigress/jdh4/utilities/job_defense_shield/violations
reply-to: rcsystems@princeton.edu
greeting-method: getent
workday-method: usa
jobstats-module-path: /usr/local/bin/jobstats
admin-reports:
  - halverson@princeton.edu
external-emails:
  u12345: first.last@gmail.com
  u98765: last.first@gmail.com
partition_renamings:
  datascience: datasci


#################################
## SHOULD BE USING MIG (ALERT) ##
#################################
should-be-using-mig-1:
  cluster: della
  partition: gpu
  gpu_util_target: "50%"
  excluded_users:
    - aturing
    - jzp
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu


##################################
## ZERO CPU UTILIZATION (ALERT) ##
##################################
zero-cpu-utilization-1:
  cluster: stellar
  partitions:
    - all
    - pppl
    - pu
  min_run_time: 60 # minutes
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu

zero-cpu-utilization-2:
  cluster: della
  partitions:
    - cpu
    - physics
  min_run_time: 60 # minutes
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu


########################################
## ZERO UTILIZATION GPU-HOURS (ALERT) ##
########################################
zero-util-gpu-hours-1:
  cluster: della
  partitions:
    - gpu
    - pli-c
    - pli-p
    - pli
  min_run_time: 10              # minutes
  gpu_hours_threshold_user:  72 # hours
  gpu_hours_threshold_admin: 24 # hours
  max_num_jobid: 2              # count


####################################
## TOO MANY CORES PER GPU (ALERT) ##
####################################
too-many-cores-per-gpu-1:
  cluster: della
  cluster_name: "Della (PLI)"
  partitions:
    - pli
    - pli-c
    - pli-p
  excluded_users:
    - aturing
    - einstein
  cores_per_gpu_target: 12
  cores_per_gpu_limit: 24
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu


########################
## LOW CPU EFFICIENCY ##
########################
low-cpu-efficiency-1:
  cluster: della
  cluster_name: "Della (cpu)"
  partitions:
    - cpu
  eff_thres_pct: 60         # percent
  eff_target_pct: 90        # percent
  proportion_thres_pct: 2   # percent
  absolute_thres_hours: 50  # cpu-hours
  num_top_users: 15         # count
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-cpu-efficiency-2:
  cluster: della
  cluster_name: "Della (physics)"
  partitions:
    - physics
  eff_thres_pct: 60
  eff_target_pct: 90
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 3
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-cpu-efficiency-3:
  cluster: stellar
  cluster_name: "Stellar (Intel)"
  partitions:
    - all
    - pppl
    - pu
    - serial
  eff_thres_pct: 60
  eff_target_pct: 90
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 15
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu


########################
## LOW GPU EFFICIENCY ##
########################
low-gpu-efficiency-1:
  cluster: della
  cluster_name: "Della (gpu)"
  partitions:
    - gpu
  eff_thres_pct: 15
  eff_target_pct: 50
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 15
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-gpu-efficiency-2:
  cluster: della
  cluster_name: "Della (pli-c)"
  partitions:
    - pli-c
  eff_thres_pct: 40
  eff_target_pct: 75
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 5
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu
    - msbc@princeton.edu

low-gpu-efficiency-3:
  cluster: della
  cluster_name: "Della (pli)"
  partitions:
    - pli
  eff_thres_pct: 40
  eff_target_pct: 75
  proportion_thres_pct: 2
  absolute_thres_hours: 50
  num_top_users: 5
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu
    - msbc@princeton.edu


#######################
## EXCESS CPU MEMORY ##
#######################
excess-cpu-memory-1:
  clusters:
    - della
  partition:
    - cpu
  combine_partitions: False
  min_run_time: 0 # minutes
  cores_per_node: 28
  tb_hours_per_day: 0
  ratio_threshold: 0.35
  mean_ratio_threshold: 0.35
  median_ratio_threshold: 0.35
  num_top_users: 10
  excluded_users:
    - aturing
    - einstein
    - vonholdt
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu

excess-cpu-memory-2:
  clusters:
    - della
  partition:
    - datasci
  combine_partitions: False
  min_run_time: 60 # minutes
  cores_per_node: 10000
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 10
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu

excess-cpu-memory-3:
  clusters:
    - stellar
  partition:
    - all
    - pppl
    - pu
    - serial
  combine_partitions: False
  min_run_time: 60 # minutes
  cores_per_node: 76.8
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 5
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
