%YAML 1.1
---
#####################
## GLOBAL SETTINGS ##
#####################
violation-logs-path: /tigress/jdh4/utilities/job_defense_shield/violations
reply-to: rcsystems@princeton.edu
greeting-method: getent
workday-method: usa
jobstats-module-path: /usr/local/bin/jobstats
email-files-path: /tigress/jdh4/utilities/job_defense_shield/email
admin-reports:
  - halverson@princeton.edu
email_suffix: "@princeton.edu"
partition_renamings:
  datascience: datasci
external-emails: # overrides
  u12345: first.last@gmail.com
  u98765: last.first@gmail.com


####################################
## GPU MODEL TOO POWERFUL (ALERT) ##
####################################
gpu-model-too-powerful-1:
  cluster: della
  partition: gpu
  min_run_time: 61 # minutes
  num_cores_threshold: 1
  gpu_util_target: "50%"
  max_num_jobid_admin: 3
  email_file: "email/gpu_model_too_powerful.txt"
  excluded_users:
    - aturing
    - jzp
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu


##################################
## ZERO CPU UTILIZATION (ALERT) ##
##################################
zero-cpu-utilization-1:
  cluster: stellar
  partitions:
    - all
    - pppl
    - pu
  min_run_time: 60 # minutes
  email_file: "email/zero_cpu_utilization.txt"
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu

zero-cpu-utilization-2:
  cluster: della
  partitions:
    - cpu
    - physics
  min_run_time: 60 # minutes
  email_file: "email/zero_cpu_utilization.txt"
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu


########################################
## ZERO UTILIZATION GPU-HOURS (ALERT) ##
########################################
zero-util-gpu-hours-1:
  cluster: della
  partitions:
    - gpu
    - pli-c
    - pli-p
    - pli
  min_run_time: 10              # minutes
  gpu_hours_threshold_user: 100 # hours
  gpu_hours_threshold_admin: 24 # hours
  max_num_jobid_admin: 2        # count
  email_file: "email/zero_util_gpu_hours.txt"
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu

####################################
## TOO MANY CORES PER GPU (ALERT) ##
####################################
too-many-cores-per-gpu-1:
  cluster: della
  partitions:
    - pli
    - pli-c
    - pli-p
  cluster_name: "Della (PLI)"
  cores_per_node: 96
  gpus_per_node: 8
  cores_per_gpu_target: 12
  cores_per_gpu_limit: 24
  min_run_time: 30 # minutes
  email_file: "email/too_many_cores_per_gpu.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu


########################
## LOW CPU EFFICIENCY ##
########################
low-cpu-efficiency-1:
  cluster: della
  partitions:
    - cpu
  eff_thres_pct: 60         # percent
  eff_target_pct: 90        # percent
  proportion_thres_pct: 2   # percent
  absolute_thres_hours: 50  # cpu-hours
  num_top_users: 15         # count
  min_run_time: 30          # minutes
  email_file: "email/low_cpu_efficiency.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-cpu-efficiency-2:
  cluster: della
  partitions:
    - physics
  eff_thres_pct: 60         # percent
  eff_target_pct: 90        # percent
  proportion_thres_pct: 2   # percent
  absolute_thres_hours: 50  # cpu-hours
  num_top_users: 3          # count
  min_run_time: 30          # minutes
  email_file: "email/low_cpu_efficiency.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-cpu-efficiency-3:
  cluster: stellar
  partitions:
    - all
    - pppl
    - pu
    - serial
  eff_thres_pct: 60         # percent
  eff_target_pct: 90        # percent
  proportion_thres_pct: 2   # percent
  absolute_thres_hours: 50  # cpu-hours
  num_top_users: 15         # count
  min_run_time: 30          # minutes
  email_file: "email/low_cpu_efficiency.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu


########################
## LOW GPU EFFICIENCY ##
########################
low-gpu-efficiency-1:
  cluster: della
  partitions:
    - gpu
  eff_thres_pct: 15         # percent
  eff_target_pct: 50        # percent
  proportion_thres_pct: 2   # percent
  absolute_thres_hours: 50  # gpu-hours
  num_top_users: 15         # count
  min_run_time: 30          # minutes
  email_file: "email/low_gpu_efficiency.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - msbc@princeton.edu

low-gpu-efficiency-2:
  cluster: della
  partitions:
    - pli-c
  eff_thres_pct: 40         # percent
  eff_target_pct: 75        # percent
  proportion_thres_pct: 2   # percent
  absolute_thres_hours: 168 # gpu-hours
  num_top_users: 5          # count
  min_run_time: 30          # minutes
  email_file: "email/low_gpu_efficiency.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu
    - msbc@princeton.edu

low-gpu-efficiency-3:
  cluster: della
  partitions:
    - pli
  eff_thres_pct: 40         # percent
  eff_target_pct: 75        # percent
  proportion_thres_pct: 2   # percent
  absolute_thres_hours: 168 # gpu-hours
  num_top_users: 3          # count
  min_run_time: 30          # minutes
  email_file: "email/low_gpu_efficiency.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
    - kl5675@princeton.edu
    - msbc@princeton.edu


###################################################
## SERIAL CODE ALLOCATING MULTIPLE CORES (ALERT) ##
###################################################
serial-using-multiple-1:
  cluster: della
  partitions:
    - cpu
  cores_per_node: 32       # (optional)
  min_run_time: 61         # minutes
  cpu_hours_threshold: 100 # cpu-hours
  lower_ratio: 0.85        # [0, 1]
  num_top_users: 5
  num_jobs_display: 10
  email_file: "email/serial_using_multiple.txt"
  max_num_jobid_admin: 3
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - halverson@princeton.edu
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com


########################
## EXCESS TIME LIMITS ##
########################
excessive-time-1:
  cluster: della
  partitions:
    - cpu
  min_run_time: 62             # minutes
  absolute_thres_hours: 10000  # cpu-hours
  mean_ratio_threshold: 20     # [0%, 100%]
  median_ratio_threshold: 20   # [0%, 100%]
  num_top_users: 5
  num_jobs_display: 10
  email_file: "email/excessive_time.txt"
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu


#######################
## EXCESS CPU MEMORY ##
#######################
excess-cpu-memory-1:
  cluster: della
  partition:
    - cpu
  combine_partitions: False
  min_run_time: 30 # minutes
  cores_per_node: 28
  tb_hours_per_day: 10
  ratio_threshold: 0.35
  mean_ratio_threshold: 0.35
  median_ratio_threshold: 0.35
  num_top_users: 10
  excluded_users:
    - aturing
    - einstein
    - vonholdt
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu

excess-cpu-memory-2:
  cluster: della
  partition:
    - datasci
  combine_partitions: False
  min_run_time: 60 # minutes
  cores_per_node: 10000
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 10
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu

excess-cpu-memory-3:
  cluster: stellar
  partition:
    - all
    - pppl
    - pu
    - serial
  combine_partitions: False
  min_run_time: 60 # minutes
  cores_per_node: 76.8
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 5
  excluded_users:
    - aturing
    - einstein
  admin_emails:
    - alerts-jobs-aaaalegbihhpknikkw2fkdx6gi@princetonrc.slack.com
    - halverson@princeton.edu
