site_name: "Job Defense Shield"
site_url: https://PrincetonUniversity.github.io/job_defense_shield/
repo_url: "https://github.com/PrincetonUniversity/job_defense_shield"
repo_name: PrincetonUniversity/job_defense_shield
nav:
  - Overview: index.md
  - Installation: setup.md
  - Configuration: configuration.md
  - Emails: emails.md
  - Alerts:
    - Your First Alert:            alert/your_first_alert.md
    - Cancel 0% GPU Jobs:          alert/cancel_gpu_jobs.md
    - Zero GPU Utilization:        alert/zero_gpu_util.md
    - Low CPU Utilization:         alert/low_cpu_util.md
    - Low GPU Utilization:         alert/low_gpu_util.md
    - Serial Allocating Multiple:  alert/serial_allocating_multiple.md
    - GPU Model Too Powerful:      alert/gpu_model_too_powerful.md
    - CPU Mem per GPU:             alert/excess_cpu_mem_per_gpu.md
    - Too Many Cores per GPU:      alert/excess_cores_per_gpu.md
    - Multinode CPU Fragmentation: alert/cpu_fragmentation.md
    - Multinode GPU Fragmentation: alert/gpu_fragmentation.md
    - Excess CPU Memory:           alert/excess_cpu_memory.md
    - Run Time Limits:             alert/time_limits.md
    - New Alert:                   alert/new_alert.md
  - Reports:
    - Overview:             reports/overview.md
    - Usage By Slurm Account: reports/account.md
  - Nodelist: nodelist.md
  - Tips: extra.md
  - Contributions: contributions.md
  - Support: support.md
  - Publications: publications.md
theme:
  name: material
  features:
    - navigation.footer
    #- content.code.copy
  palette:
    # light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: red
      accent: blue
    # dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PrincetonUniversity/job_defense_shield
  generator: false

copyright: "&copy;2025 Princeton University. All rights reserved."
